name: Default
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ci-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ci.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/ci:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  read-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read-version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from world.wit
        id: read-version
        run: |
          VERSION=$(grep -o 'package ardo314:math@[0-9]*\.[0-9]*\.[0-9]*' wit/world.wit | sed 's/package ardo314:math@//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

  test:
    runs-on: ubuntu-latest
    needs: build-ci-image
    container:
      image: ghcr.io/${{ github.repository }}/ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check that it compiles
        run: cargo check

      - name: Run tests
        run: cargo test --verbose

  build:
    runs-on: ubuntu-latest
    needs: build-ci-image
    container:
      image: ghcr.io/${{ github.repository }}/ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build component
        run: cargo component build --release

      - name: Upload WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: math-rs-wasm
          path: target/wasm32-wasip1/release/math_rs.wasm
          retention-days: 30

  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    needs: [read-version, build, build-ci-image]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Download WASM artifact
        uses: actions/download-artifact@v4
        with:
          name: math-rs-wasm

      - name: Verify artifact
        run: ls -la target/wasm32-wasip1/release/math_rs.wasm

      - name: Publish component
        run: wkg oci push ardo314/math-rs:${{ needs.read-version.outputs.version }} target/wasm32-wasip1/release/math_rs.wasm -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
